#!/usr/bin/env bash

DIRNAME=/tmp/codalab
mkdir -p $DIRNAME
UUID=$(cl work -u)
FILENAME=$DIRNAME/$UUID.md
if [[ -f "$FILENAME" ]]; then
  echo File $FILENAME already exists.
  exit 1
fi

cl status | sed 's/^worksheet.*/\x1b[1;33m&\x1b[0m/;s+http://localhost:12800$+\x1b[1;32mNLP\x1b[0m+;s+local$+\x1b[1;31mlocal\x1b[0m+'
read -p "Is this good (y/n)? " answer
[[ "$answer" == y ]] || exit 1

function CodaLabSave() {
  UUID=$1
  LOCAL=$2
  BASE=$2-base
  REMOTE=$2-remote
  echo "Saving remote copy to $REMOTE ..."
  cl print -r $UUID > $REMOTE
  diff -q $BASE $REMOTE
  if [[ "$?" -ne 0 ]]; then
    echo "Remote modified. Launching meld ..."
    meld $LOCAL $REMOTE
  fi
  # Assume that $LOCAL has the correct version
  echo "Saving worksheet $UUID ..."
  cl wedit $UUID -f $LOCAL
  CodaLabLoad $1 $2
}

function CodaLabLoad() {
  UUID=$1
  LOCAL=$2
  BASE=$2-base
  echo "Saving remote copy to $BASE ..."
  cl print -r $UUID > $BASE
  cp $BASE $LOCAL
}

export -f CodaLabSave
export -f CodaLabLoad
CodaLabLoad $UUID $FILENAME
echo Editing $FILENAME ...
UUID=$UUID vi $FILENAME
CodaLabSave $UUID $FILENAME
rm $FILENAME
