#!/usr/bin/env bash

# Change the difftool here:
DIFFTOOL=meld
if [[ -z "$DISPLAY" ]]; then
  DIFFTOOL=vimdiff
fi

DIRNAME=/tmp/codalab
mkdir -p $DIRNAME
UUID=$(cl work -u)
FILENAME=$DIRNAME/$UUID.md
if [[ -f "$FILENAME" ]]; then
  echo File $FILENAME already exists.
  exit 1
fi

cl status | sed '
  s`^worksheet.*`\x1b[1;33m&\x1b[0m`;
  s`https*://localhost:12800$`\x1b[1;32mNLP\x1b[0m`
  s`https*://codalab.org/bundleservice$`\x1b[1;36mCodaLab.org\x1b[0m`
  s`local$`\x1b[1;31mlocal\x1b[0m`'
read -p "Is this good (y/n)? " answer
[[ "$answer" == y ]] || exit 1

function CodaLabSave() {
  UUID=$1
  LOCAL=$2
  BASE=$2-base
  REMOTE=$2-remote
  echo "Grabbing remote copy ..."
  cl print -r $UUID > $REMOTE
  diff -q $BASE $LOCAL
  LOCAL_CHANGED="$?"
  diff -q $BASE $REMOTE
  REMOTE_CHANGED="$?"
  if [[ $LOCAL_CHANGED -eq 0 ]]; then
    if [[ $REMOTE_CHANGED -ne 0 ]]; then
      echo "Refreshing ..."
      cp $REMOTE $BASE && cp $REMOTE $LOCAL
    else
      echo "Nothing to do."
    fi
  else
    if [[ $REMOTE_CHANGED -ne 0 ]]; then
      echo "Remote modified. Launching $DIFFTOOL ..."
      $DIFFTOOL $LOCAL $REMOTE
    fi
    echo "Saving ..."
    cl wedit $UUID -f $LOCAL
    CodaLabLoad $UUID $LOCAL
  fi
}

function CodaLabLoad() {
  UUID=$1
  LOCAL=$2
  BASE=$2-base
  cl print -r $UUID > $BASE
  cp $BASE $LOCAL
}

export -f CodaLabSave
export -f CodaLabLoad
export UUID
CodaLabLoad $UUID $FILENAME
echo Editing $FILENAME ...
vi -c ":set nowrap" $FILENAME
CodaLabSave $UUID $FILENAME
rm $FILENAME
